spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.scaffoldops-pre.svc.cluster.local:9092}

app:
  lifecycle:
    base-url: ${GENERATOR_API_BASE_URL:http://generator-api-service.scaffoldops-pre.svc.cluster.local}
