apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generator-worker-artifacts-pvc
  namespace: scaffoldops-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
