apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-worker
  namespace: scaffoldops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator-worker
  template:
    metadata:
      labels:
        app: generator-worker
    spec:
      volumes:
        - name: generator-worker-data
          persistentVolumeClaim:
            claimName: generator-worker-artifacts-pvc
      containers:
        - name: generator-worker
          image: victodomvar/scaffoldops-generator-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: generator-worker-data
              mountPath: /var/lib/generator-worker
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_CONSUMER_GROUP
              value: "generator-worker"
            - name: GENERATION_REQUESTED_TOPIC
              value: "generation-requested"
            - name: ARTIFACT_CLEANUP_REQUESTED_TOPIC
              value: "artifact-cleanup-requested"
            - name: GENERATOR_API_BASE_URL
              value: "http://generator-api:8081/api/generator/v1"
            - name: GENERATOR_API_LIFECYCLE_HTTP_ENABLED
              value: "true"
            - name: GENERATOR_API_AUTH_MODE
              value: "client-credentials"
            - name: GENERATOR_API_TOKEN_URL
              value: "http://keycloak.security.svc.cluster.local:8080/realms/scaffoldops-dev/protocol/openid-connect/token"
            - name: GENERATOR_API_CLIENT_ID
              value: "scaffoldops-generator-worker"
            - name: GENERATOR_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: generator-api-worker-client
                  key: client-secret
            - name: GENERATION_MANIFEST_OUTPUT_DIR
              value: "/var/lib/generator-worker/manifests"
            - name: GENERATION_HANDOFF_STATE_DIR
              value: "/var/lib/generator-worker/handoff"
            - name: DOCKER_COMMAND
              value: "docker"
            - name: GENERATOR_DOCKER_BUILD_ENABLED
              value: "false"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
