apiVersion: v1
kind: Service
metadata:
  name: generator-api
  namespace: scaffoldops-dev
spec:
  selector:
    app: generator-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
