apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scaffoldops-dev

resources:
  - generator-api-alias-service.yaml
  - generator-worker-artifacts-pvc.yaml
  - generator-worker-deployment.yaml
  - generator-worker-service.yaml
